# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (C) 2026 the FreeCAD-OpenStudio bridge contributors
#
# This program is free software: you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the
# Free Software Foundation, either version 3 of the License, or (at your
# option) any later version.  See LICENSE for the full text.

"""Hang an elevation sketch off each facade of the imported geometry.

Run under FreeCAD's bundled Python:

    "C:/Program Files/FreeCAD 1.1/bin/python.exe" fc_seed_openings.py \
        FloorplanTest-02.FCStd

Sketching fenestration by hand is only laborious because of the setup: finding
the wall plane, orienting it, and projecting enough of the model into it to
have something to snap to.  All three are derivable from the geometry the
bridge already generated, so this does them.

For every distinct exterior wall plane in the document it creates one sketch:

  * **attached to the traced plan** -- ThreePointsNormal on the wall
    centerline that produced the facade, so the sketch stands up on the line
    you drew.  Move that wall in the plan and the elevation follows.
  * **oriented like an elevation** -- sketch +Y is up, sketch +Z points out of
    the building, so you are looking at the facade from outside.  An
    AttachmentOffset pins the origin at the left-hand end of the facade at
    z = 0, so sketch x is "distance along the elevation" and sketch y is
    "height above the datum", which is how the drawings are dimensioned.
  * **referenced to the plan** -- that same wall centerline is projected in
    as external geometry, so the elevation has a datum line to snap to, and
    one that moves when the wall does.

**Why the plan and not the wall face.**  These sketches used to attach to the
largest imported wall face (MapMode FlatFace), which reads well -- the sketch
plane *is* the wall -- and is a trap.  `import` replaces a surface's Shape
outright, so after the model changes, FlatFace re-derives the frame from a new
face whose parametrisation need not match the old one.  Re-importing after a
roof change turned three of these sketches through 180 degrees and slid them
up to 39 m, dragging 20 of 27 drawn outlines with them, and the only sign was
that the openings ended up somewhere nobody drew them.

The plan is the source everything else is derived from and it is not
regenerated by anything, so it is the thing to hang off.

**The only external geometry is that same plan line.**  These sketches used to
project the imported facade's edges in as snap targets, which put a reference
to the model inside a sketch that has to depend only on the drawing -- and a
reference to the one kind of geometry `import` replaces outright.  What is
projected now is the traced wall centerline the sketch is already attached to,
so the elevation carries its own datum line and the extent of the facade and
owes the model nothing.

Only that one edge, not every plan edge in the plane.  Measured on
FloorplanTest-02: seven plan edges lie in the south plane -- the envelope line
plus the per-tenant walls drawn along it -- and three more on the storey
above.  Ten overlapping references are nine ambiguous snap targets.

Unless --empty is given, the model's existing subsurfaces on that plane are
drawn in as editable, constrained rectangles.  Correcting one is then a drag,
and fc_export_openings.py -> apply_openings.py puts the correction back.

Re-running is safe: attachment and orientation are refreshed, the plan-line
reference is added only if it is not already there, and geometry you have
drawn is never touched.  Re-running an older document migrates it -- the
attachment moves to the plan and references to the imported model are dropped
-- without moving a single outline.
"""

import argparse
import time
import math
import os
import shutil
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

import FreeCAD  # noqa: E402
import Part  # noqa: E402
import Sketcher  # noqa: E402

import fcbridge  # noqa: E402

MM_PER_M = 1000.0

# Two faces are in the same plane when their normals agree to this, and their
# offsets to PLANE_TOL_MM.  A wall traced in CAD is exact, so these only have
# to absorb OCC's own rounding.
NORMAL_TOL = 1e-4
PLANE_TOL_MM = 0.5

# Below this a "wall plane" is a sliver, not a facade worth its own sketch.
MIN_PLANE_AREA_M2 = 0.5

# Facade naming lives in fcbridge so the shading exporter names a canopy by
# the same rule that named the door beneath it.
COMPASS = fcbridge.COMPASS
plan_azimuth = fcbridge.plan_azimuth
compass_of = fcbridge.compass_of

SKETCH_PROPS = [
    ("OS_OpeningSketch", "App::PropertyBool"),
    ("OS_Facade", "App::PropertyString"),
    ("OS_PlaneNormal", "App::PropertyString"),
    ("OS_PlaneOffset", "App::PropertyLength"),
    ("OS_HostSurfaces", "App::PropertyStringList"),
]


# --------------------------------------------------------------------------
# finding the facades
# --------------------------------------------------------------------------

def wall_faces(doc):
    """(object, face) for every exterior wall the bridge generated."""
    out = []
    for obj in doc.Objects:
        if not getattr(obj, "OS_SurfaceName", None):
            continue
        if getattr(obj, "OS_SubSurfaceType", None):
            continue
        if getattr(obj, "OS_SurfaceType", "") != "Wall":
            continue
        if getattr(obj, "OS_BoundaryCondition", "") != "Outdoors":
            continue
        faces = getattr(obj.Shape, "Faces", [])
        if faces:
            out.append((obj, faces[0]))
    return out


def plane_of(face):
    """(unit normal, signed offset) of a planar face, in mm."""
    surface = face.Surface
    axis = getattr(surface, "Axis", None)
    if axis is None:
        return None
    n = FreeCAD.Vector(axis.x, axis.y, axis.z).normalize()
    # A face's parametric normal may point either way; the shape's own
    # orientation says which is outward.
    if face.Orientation == "Reversed":
        n = n.negative()
    return n, n.dot(face.Vertexes[0].Point)


def group_planes(pairs):
    """Bucket wall faces into planes, largest total area first."""
    groups = []
    for obj, face in pairs:
        found = plane_of(face)
        if found is None:
            continue
        n, off = found
        for g in groups:
            if g["normal"].dot(n) > 1.0 - NORMAL_TOL and \
                    abs(g["offset"] - off) < PLANE_TOL_MM:
                g["members"].append((obj, face))
                g["area"] += face.Area
                break
        else:
            groups.append({"normal": n, "offset": off, "area": face.Area,
                           "members": [(obj, face)]})
    groups = [g for g in groups
              if g["area"] / (MM_PER_M ** 2) >= MIN_PLANE_AREA_M2]
    groups.sort(key=lambda g: -g["area"])
    return groups


def room_number(space_name):
    """'037-501-Mechanical Room' -> '501'."""
    parts = (space_name or "").split("-")
    if len(parts) >= 3 and parts[0].strip().isdigit():
        return parts[1].strip()
    return ""


def name_planes(groups):
    """Give each plane a facade name, disambiguated where one repeats."""
    for g in groups:
        g["compass"] = compass_of(g["normal"])
    used = set()
    for g in groups:
        base = g["compass"]
        if base not in used:
            g["facade"] = base
            used.add(base)
            continue
        spaces = sorted({getattr(o, "OS_SpaceName", "")
                         for o, _ in g["members"]})
        tag = room_number(spaces[0]) if len(spaces) == 1 else ""
        candidate = "%s %s" % (base, tag) if tag else base
        index = 2
        while candidate in used:
            candidate = "%s %d" % (base, index)
            index += 1
        g["facade"] = candidate
        used.add(candidate)
    return groups


# --------------------------------------------------------------------------
# the elevation frame
# --------------------------------------------------------------------------

def elevation_placement(group):
    """Where the sketch should sit: an elevation view of this facade.

    +Y up, +Z out of the building, origin at the left-hand end of the facade
    (seen from outside) on the z = 0 datum.  So sketch x is distance along the
    elevation and sketch y is height, exactly as the drawings dimension it.
    """
    zd = FreeCAD.Vector(group["normal"])
    up = FreeCAD.Vector(0, 0, 1)
    yd = up - zd * up.dot(zd)
    if yd.Length < 1e-9:
        return None                       # horizontal "wall" -- not a facade
    yd.normalize()
    xd = yd.cross(zd)
    xd.normalize()

    pts = [v.Point for _, face in group["members"] for v in face.Vertexes]
    p0 = pts[0]
    u_min = min((p - p0).dot(xd) for p in pts)
    origin = p0 + xd * u_min + yd * (-p0.z / yd.z)

    matrix = FreeCAD.Matrix(xd.x, yd.x, zd.x, origin.x,
                            xd.y, yd.y, zd.y, origin.y,
                            xd.z, yd.z, zd.z, origin.z,
                            0.0, 0.0, 0.0, 1.0)
    return FreeCAD.Placement(matrix)


def plan_wall_edge(plan_sketches, group):
    """(plan sketch, edge index, vertex index) for this facade's wall line.

    The bridge traces wall *centerlines* and OpenStudio surfaces are
    infinitely thin, so a facade plane and the plan line that produced it are
    the same plane.  That makes the traced line findable from the plane alone,
    with nothing to configure.

    The extra vertex is what ThreePointsNormal needs: three points define the
    horizontal plane it stands the facade up perpendicular to, and the wall
    line only supplies two.  The furthest plan vertex from that line is picked
    because it is the least degenerate choice and the same one every run.
    """
    normal, offset = group["normal"], group["offset"]
    best = None
    for plan in plan_sketches:
        shape = getattr(plan, "Shape", None)
        if shape is None or not shape.Edges:
            continue
        elevation = fcbridge.story_elevation_m(plan)
        for index, edge in enumerate(shape.Edges, start=1):
            points = [v.Point for v in edge.Vertexes]
            if len(points) != 2:
                continue                    # not a straight segment
            if any(abs(normal.dot(p) - offset) > PLANE_TOL_MM for p in points):
                continue
            length = (points[1] - points[0]).Length
            # Lowest storey first, then the longest run in the plane: the
            # facade's main line rather than a stub beside a doorway.
            rank = (elevation, -length)
            if best is None or rank < best[0]:
                best = (rank, plan, index, points)
    if best is None:
        return None

    _rank, plan, index, points = best
    direction = points[1] - points[0]
    direction.normalize()
    far, far_distance = None, -1.0
    for number, vertex in enumerate(plan.Shape.Vertexes, start=1):
        offset_vector = vertex.Point - points[0]
        across = (offset_vector
                  - direction * offset_vector.dot(direction)).Length
        if across > far_distance:
            far, far_distance = number, across
    if far is None or far_distance < PLANE_TOL_MM:
        return None                         # the whole plan is one line
    return plan, index, far


def attach(doc, sketch, group, want, plan_sketches):
    """Attach the sketch to the traced plan, landing on `want`.

    Not to the wall face the model generated, which is where this used to
    attach and what made it fragile: `import` replaces a surface's Shape
    outright, and FlatFace then re-derives the frame from a new face whose
    parametrisation need not match the old one.  Re-importing after a roof
    change flipped three of these sketches through 180 degrees and slid them
    up to 39 m, taking every opening drawn on them along.

    The traced plan is the source everything else is derived from, so it is
    the thing to hang off.  ThreePointsNormal stands the facade up on the wall
    centerline; the AttachmentOffset then corrects OCC's choice of origin to
    the elevation frame, exactly as before, and the sketch still follows the
    wall when the plan moves.

    Returns (host description, residual mm, note, anchor) where anchor is the
    (plan sketch, edge index) it stood up on, or None when it had to fall back
    to model geometry.  The caller projects that same edge in as the sketch's
    only external reference, so what you snap to and what the sketch is
    attached to cannot drift apart.
    """
    found = plan_wall_edge(plan_sketches, group)
    if found is None:
        # A facade the plan does not draw -- an interior court, or a wall
        # generated by intersection rather than traced.  Fall back to the old
        # attachment rather than leaving the sketch floating, and say so.
        host, _face = max(group["members"], key=lambda m: m[1].Area)
        sketch.AttachmentSupport = [(host, ("Face1",))]
        sketch.MapMode = "FlatFace"
        sketch.AttachmentOffset = FreeCAD.Placement()
        doc.recompute()
        sketch.AttachmentOffset = sketch.Placement.inverse().multiply(want)
        doc.recompute()
        return (getattr(host, "OS_SurfaceName", host.Name),
                (sketch.Placement.Base - want.Base).Length,
                "no traced wall line in this plane -- still on model geometry",
                None)

    plan, edge_index, vertex_index = found
    sketch.AttachmentSupport = [(plan, ("Edge%d" % edge_index,
                                        "Vertex%d" % vertex_index))]
    sketch.MapMode = "ThreePointsNormal"
    sketch.MapReversed = False
    sketch.AttachmentOffset = FreeCAD.Placement()
    doc.recompute()

    # Three points wound the other way give the same plane facing inward.
    facing = sketch.Placement.Rotation.multVec(FreeCAD.Vector(0, 0, 1))
    if facing.dot(group["normal"]) < 0:
        sketch.MapReversed = True
        doc.recompute()

    sketch.AttachmentOffset = sketch.Placement.inverse().multiply(want)
    doc.recompute()

    return ("%s Edge%d" % (plan.Label, edge_index),
            (sketch.Placement.Base - want.Base).Length, None,
            (plan, edge_index))


# --------------------------------------------------------------------------
# external geometry
# --------------------------------------------------------------------------

def strip_external(sketch):
    """Drop every external geometry reference from a sketch.

    Returns (references removed, constraints lost).  Deleting a reference
    deletes any constraint made against it, which is why the count is
    reported: those elements become under-constrained.  They do not *move* --
    a Sketcher constraint holds geometry in place, it does not generate it --
    so this is a loosening, not an edit.
    """
    before = len(sketch.Constraints)
    removed = 0
    # delExternal indexes external *elements*, while ExternalGeometry lists
    # them grouped by the object they came from -- one entry can hold four
    # edges.  So walking the entry indices deletes a fraction of them and
    # leaves the rest looking removed.  Drain from the front instead, with a
    # bound, since a delete that stops shrinking the list would otherwise spin.
    while sketch.ExternalGeometry and removed < 10000:
        sketch.delExternal(0)
        removed += 1
    return removed, before - len(sketch.Constraints)


def external_refs(sketch):
    """The sketch's external geometry flattened to (object, subelement).

    ExternalGeometry groups references by the object they came from -- one
    entry can hold several edges -- so anything counting or testing them has
    to expand it first.
    """
    refs = []
    for entry in sketch.ExternalGeometry:
        obj, subs = entry[0], entry[1]
        for sub in subs:
            refs.append((obj, sub))
    return refs


def foreign_external(sketch, plan_names):
    """External references pointing at something other than the plan.

    That means the imported model, which is what these sketches are being got
    off: a reference to a surface whose Shape `import` replaces outright.
    """
    return [(obj, sub) for obj, sub in external_refs(sketch)
            if obj.Name not in plan_names]


def add_plan_edge(sketch, anchor):
    """Project the plan line this elevation stands on into the sketch.

    The same edge the attachment uses, deliberately: an elevation wants a
    datum line and the ends of the facade to snap to, and taking it from the
    edge the sketch is already attached to means the reference cannot end up
    describing a different wall from the one the sketch stands on.

    Returns 1 if it was added, 0 if it was already there.  Never removes, so a
    refresh cannot cost a constraint made against it.
    """
    if anchor is None:
        return 0
    plan, edge_index = anchor
    sub = "Edge%d" % edge_index
    for obj, have in external_refs(sketch):
        if obj.Name == plan.Name and have == sub:
            return 0
    try:
        sketch.addExternal(plan.Name, sub)
    except Exception as exc:                                # noqa: BLE001
        print("      could not reference %s %s: %s" % (plan.Label, sub, exc))
        return 0
    return 1


# --------------------------------------------------------------------------
# seeding the model's own subsurfaces
# --------------------------------------------------------------------------

def subsurfaces_on(doc, group):
    """Model subsurfaces lying in this plane, by host surface name."""
    hosts = {getattr(o, "OS_SurfaceName", "") for o, _ in group["members"]}
    out = []
    for obj in doc.Objects:
        if not getattr(obj, "OS_SubSurfaceType", None):
            continue
        if getattr(obj, "OS_HostSurface", "") not in hosts:
            continue
        out.append(obj)
    return out


def draw_outline(sketch, points):
    """Add a closed, coincident-constrained polygon in sketch coordinates.

    Horizontal and vertical constraints go on only where the segment already
    is, to the micron.  That makes an ordinary rectangular opening behave like
    one when you drag it, without imposing anything on a raked or angled head.
    """
    first = sketch.GeometryCount
    n = len(points)
    for i in range(n):
        a, b = points[i], points[(i + 1) % n]
        sketch.addGeometry(
            Part.LineSegment(FreeCAD.Vector(a[0], a[1], 0),
                             FreeCAD.Vector(b[0], b[1], 0)), False)
    for i in range(n):
        sketch.addConstraint(Sketcher.Constraint(
            "Coincident", first + i, 2, first + (i + 1) % n, 1))
    for i in range(n):
        a, b = points[i], points[(i + 1) % n]
        if abs(a[1] - b[1]) < 1e-3 and abs(a[0] - b[0]) > 1e-3:
            sketch.addConstraint(Sketcher.Constraint("Horizontal", first + i))
        elif abs(a[0] - b[0]) < 1e-3 and abs(a[1] - b[1]) > 1e-3:
            sketch.addConstraint(Sketcher.Constraint("Vertical", first + i))
    return n


def seed_from_model(doc, sketch, group):
    inverse = sketch.Placement.inverse()
    count = 0
    for obj in subsurfaces_on(doc, group):
        wires = getattr(obj.Shape, "Wires", [])
        if not wires:
            continue
        pts = [inverse.multVec(v.Point) for v in wires[0].OrderedVertexes]
        if len(pts) < 3:
            continue
        if max(abs(p.z) for p in pts) > PLANE_TOL_MM:
            continue
        draw_outline(sketch, [(p.x, p.y) for p in pts])
        count += 1
    return count


# --------------------------------------------------------------------------

def ensure_props(sketch):
    for name, ptype in SKETCH_PROPS:
        if not hasattr(sketch, name):
            sketch.addProperty(ptype, name, "OpenStudio",
                               "FreeCAD to OpenStudio bridge")


def safe_name(text):
    cleaned = "".join(ch if ch.isalnum() else "_" for ch in text)
    return ("OS_Elev_%s" % cleaned)[:60]


def find_sketch(doc, facade):
    for obj in doc.Objects:
        if obj.TypeId != "Sketcher::SketchObject":
            continue
        if getattr(obj, "OS_OpeningSketch", False) and \
                getattr(obj, "OS_Facade", "") == facade:
            return obj
    return doc.getObject(safe_name(facade))


def backup(path):
    stamp = time.strftime("%Y%m%d-%H%M%S")
    stem, ext = os.path.splitext(path)
    dest = "%s.bak-%s%s" % (stem, stamp, ext)
    shutil.copy2(path, dest)
    return dest


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("fcstd")
    ap.add_argument("--facade", action="append",
                    help="only this facade (repeatable); default is all")
    ap.add_argument("--empty", action="store_true",
                    help="do not draw the model's existing subsurfaces in")
    ap.add_argument("--no-external", action="store_true",
                    help="do not project the plan line in. The sketch is "
                         "still attached to it; you just get no line to "
                         "snap to")
    ap.add_argument("--external", action="store_true",
                    help=argparse.SUPPRESS)     # used to mean "pull the
                                                # imported wall edges in".
                                                # Accepted and ignored so an
                                                # existing command still runs.
    ap.add_argument("--keep-external", action="store_true",
                    help="leave references to the imported model that are "
                         "already there instead of removing them")
    ap.add_argument("--dry-run", action="store_true",
                    help="report the facades and change nothing")
    args = ap.parse_args()

    path = os.path.abspath(args.fcstd)
    doc = fcbridge.open_document(path)
    pairs = wall_faces(doc)
    if not pairs:
        raise SystemExit(
            "no exterior wall faces in %s.\nRun  .\\bridge.ps1 import "
            "<surfaces.json> --into %s  first."
            % (os.path.basename(path), os.path.basename(path)))

    north = fcbridge.north_axis_deg(doc)
    groups = name_planes(group_planes(pairs))
    print("%d exterior wall plane(s) in %s"
          % (len(groups), os.path.basename(path)))
    if north:
        print("  facade names are plan north, as on the elevation sheets; "
              "the building's\n  north axis is %.1f deg, so true bearings "
              "differ by that much." % north)
    print("  %-14s %5s %9s %9s  %s"
          % ("facade", "walls", "area m2", "true az", "plane"))
    for g in groups:
        n = g["normal"]
        print("  %-14s %5d %9.1f %8.1f`  n (%.2f %.2f %.2f) @ %.3f m"
              % (g["facade"], len(g["members"]), g["area"] / MM_PER_M ** 2,
                 (plan_azimuth(n) + north) % 360.0,
                 n.x, n.y, n.z, g["offset"] / MM_PER_M))

    wanted = set(args.facade or [])
    if wanted:
        unknown = wanted - {g["facade"] for g in groups}
        if unknown:
            raise SystemExit("no such facade: %s" % ", ".join(sorted(unknown)))
        groups = [g for g in groups if g["facade"] in wanted]

    if args.dry_run:
        print("\ndry run -- nothing written")
        return

    plan_sketches = fcbridge.story_sketches(doc)
    if not plan_sketches:
        raise SystemExit(
            "no sketch has OS_Include set, so there is no traced plan to hang "
            "the\nelevations off.  Set the story properties first.")
    plan_names = {s.Name for s in plan_sketches}

    if args.external:
        print("\n--external no longer pulls the imported wall edges in; the "
              "plan line\nthese sketches stand on is projected instead, and "
              "is all they reference.")

    print("\nbackup: %s" % os.path.basename(backup(path)))
    made = refreshed = stripped = constraints_lost = 0
    print()
    for g in groups:
        want = elevation_placement(g)
        if want is None:
            print("  %-14s skipped -- not a vertical facade" % g["facade"])
            continue

        sketch = find_sketch(doc, g["facade"])
        if sketch is None:
            sketch = doc.addObject("Sketcher::SketchObject",
                                   safe_name(g["facade"]))
            sketch.Label = "Openings %s" % g["facade"]
            fresh = True
            made += 1
        else:
            fresh = False
            refreshed += 1

        ensure_props(sketch)
        sketch.OS_OpeningSketch = True
        sketch.OS_Facade = g["facade"]
        sketch.OS_PlaneNormal = "%.6f %.6f %.6f" % (
            g["normal"].x, g["normal"].y, g["normal"].z)
        # A Length is stored in FreeCAD's internal unit, so the offset goes in
        # as the millimetres it already is -- no division, and no _m suffix
        # promising a unit the property now carries itself.
        sketch.OS_PlaneOffset = g["offset"]
        sketch.OS_HostSurfaces = sorted(
            getattr(o, "OS_SurfaceName", "") for o, _ in g["members"])

        host, residual, note, anchor = attach(doc, sketch, g, want,
                                              plan_sketches)
        edges = dropped = lost = 0

        # References to the imported model go first, so what is left is the
        # drawing.  Only when there are any: draining and re-adding the plan
        # line would cost every constraint made against it, for nothing.
        if foreign_external(sketch, plan_names) and not args.keep_external:
            dropped, lost = strip_external(sketch)
            stripped += dropped
            constraints_lost += lost
        if not args.no_external:
            edges = add_plan_edge(sketch, anchor)
        seeded = 0
        if fresh and not args.empty:
            seeded = seed_from_model(doc, sketch, g)
        doc.recompute()

        extent = [0.0, 0.0]
        pts = [sketch.Placement.inverse().multVec(v.Point)
               for _, f in g["members"] for v in f.Vertexes]
        extent = [max(p.x for p in pts) / MM_PER_M,
                  max(p.y for p in pts) / MM_PER_M]
        print("  %-14s %-9s on %-22s %.1f x %.1f m%s%s%s"
              % (g["facade"], "created" if fresh else "refreshed", host,
                 extent[0], extent[1],
                 ", plan line projected in" if edges else "",
                 ", %d opening(s) drawn in" % seeded if seeded else "",
                 "  ** off by %.3f mm **" % residual if residual > 1e-6
                 else ""))
        if note:
            print("      note: %s" % note)

    restored = fcbridge.save_document(doc)
    print("\nsaved %s%s" % (os.path.basename(path),
                            " (%d view entries restored)" % restored
                            if restored else ""))
    print("  %d sketch(es) created, %d refreshed" % (made, refreshed))
    if stripped:
        print("  %d external geometry reference(s) removed, %d constraint(s) "
              "with them" % (stripped, constraints_lost))
        print("  Those referenced the imported model, which is the one thing "
              "these sketches")
        print("  must not depend on -- `import` replaces a surface's Shape "
              "outright.  Nothing")
        print("  moved: a constraint holds geometry, it does not place it. "
              "But %d element(s)" % constraints_lost)
        print("  are now free to drag, and the plan line is there to "
              "re-constrain them to.")
    print("\nIn FreeCAD: open a sketch, draw each opening as a closed outline,"
          "\nthen\n"
          "  .\\bridge.ps1 openings %s --out openings.json\n"
          "  .\\bridge.ps1 apply <model>.osm openings.json"
          % os.path.basename(path))


if __name__ == "__main__":
    main()
