# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (C) 2026 the FreeCAD-OpenStudio bridge contributors
#
# This program is free software: you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the
# Free Software Foundation, either version 3 of the License, or (at your
# option) any later version.  See LICENSE for the full text.

"""Find air-boundary surfaces and size their air exchange from the opening.

Run under the bridge venv (system Python 3.12 + openstudio 3.11.0):

    osvenv/Scripts/python.exe find_air_boundaries.py \
        runs/mybuilding.osm \
        runs/floorplans/mybuilding.json

Prints a report and the exact `assign_air_boundary_construction` arguments to
apply.  --apply-json emits those as JSON instead, for piping.

Four rules, all stated in terms of the floor plan rather than the built model:

1.  **A shaft.** Two rooms on different stories with the *same* footprint --
    a stair, a lift shaft, a duct riser -- are one continuous volume that the
    bridge is forced to model as one space per story.  Their shared
    floor/ceiling is not a real construction, so it gets an air boundary.

2.  **A mezzanine edge.** A wall between a mezzanine and a space that spans
    more than its own story (one carrying an OS_Height override) is a
    guardrail, not a wall.

3.  **A corridor cross-section.** A wall that slices a corridor square across
    its run is a modelling division, not a construction -- the corridor is one
    continuous volume and the plan cut it into spaces.  The test is the one
    that reads off the drawing, that the wall is narrow compared with the
    length of the hallway, plus two guards that stop it firing on the
    corridor's long side.  See "Corridors" below.

4.  **An open stair edge.** A stair labelled "Open Stair" is a corridor stood
    on end.  Its long SIDES, where they face a space spanning storeys or a
    mezzanine, are guardrail edges and are taken.  Its ENDS are not: one per
    storey is the way in and the other is the wall behind the flight, and the
    plan does not carry the arrow that says which.  A plain "Stair" is
    assumed enclosed and gets nothing.

Why not read the footprints back out of the .osm: intersectSurfaces splits a
mezzanine's floor into one fragment per room beneath it, and a fragment can
coincide exactly with the small room below it.  Four such coincidences show up
in FloorplanTest-02 -- 203 RR under 205 Mezzanine among them -- and every one
of them would be a false shaft.  The exported JSON holds whole rooms, before
any splitting, so it cannot make that mistake.

Surface names are regenerated by every full build, so this is re-run after one
rather than its output being kept.  An incremental update_osm_geometry.py
--apply keeps the assignment on every space it does not rebuild.


Sizing the air exchange
-----------------------

EnergyPlus takes one air-change rate per Construction:AirBoundary and applies
it "using the volume of the smaller zone as the basis" (Energy+.idd, field N1
of Construction:AirBoundary).  One rate can therefore only be right for one
pair of spaces, so openings are grouped by space pair and each pair gets its
own construction.

Buoyancy drives the exchange, and the two opening orientations are different
problems:

**Vertical opening** (a mezzanine edge) -- counterflow through a tall aperture,
the Brown & Solvason result used for interzone flow in ASHRAE Fundamentals and
as the large-opening model in EnergyPlus's own AirflowNetwork:

    Q = (Cd / 3) * W * H^1.5 * sqrt(g * dT / T_mean)

**Horizontal opening** (a stair or shaft penetrating a floor) -- Rayleigh-
Taylor exchange through an aperture in a thin horizontal partition, Epstein
(1988), in the thin-plate regime that a ~0.2 m slab with a ~3 m opening sits
well inside (L/D of about 0.06, against a regime boundary at 0.15):

    Q = C_h * sqrt((g * dT / T_mean) * D^5)

Q is the one-way exchange; the same volume flows back the other way, which is
what an air change *is*, so ACH = Q * 3600 / V_smaller.

dT is NOT a free parameter here.  An air boundary is used precisely where two
zones are open to each other, and that exchange is what holds them together, so
they equilibrate: 0.5 K is the accepted working figure and the default.  A
large dT and an open boundary are mutually exclusive -- 10 K between adjacent
commercial zones means an enclosure, a cold store or a sauna, which would not
have an open boundary in the first place.  --delta-t is for an engineer's
judgement on a genuine edge case, not for exploring a range.

There is a useful consistency in this: the rates come out high, and that is
exactly why the 0.5 K premise holds.  Above roughly 10 ACH the coupling
saturates -- the zones track each other closely whatever the exact rate -- so
what the number really settles is whether the two spaces should have been one
zone, not how hard to mix them.

The coefficients are documented defaults, not measurements of this building.
The report prints all of them so they can be checked rather than taken on faith.


Corridors
---------

"Narrow compared with the length of the hallway" is the right instinct, and on
its own it is not enough: the width of a wall says nothing about which side of
the corridor it is on.  Measured on FloorplanTest-02's own hallways:

    101a Hallway, 8.58 m long x 1.65 m wide

        wall to 101  Lobby        1.65 m   w/L 0.19   <- an open end
        wall to 101b Hallway 6    1.65 m   w/L 0.19   <- an open end
        wall to 102  Office       1.29 m   w/L 0.15   <- a piece of the side

The office frontage is the *narrowest* wall on that corridor, and it is a wall.
So two more conditions come in, both saying the same thing -- that the surface
is a slice through the corridor rather than a fragment of its flank:

  * it spans the corridor's own width (w / W_corridor near 1);
  * it stands square to the corridor's run.

The three together select exactly the corridor ends here and reject the office
fragment (w/W 0.78), the restrooms off 101b (w/W 1.46), the stair alongside
101a (parallel to the run) and the shop wall on 101c.

Length and width are measured on the footprint's minimum-area bounding
rectangle rather than on x and y, because the building need not be axis-aligned
-- this one is drawn on a 45 degree north axis.

An L-junction satisfies the square-to-the-run test from only ONE of its two
corridors: where 101a ends into the flank of 101b, 101a sees a cross-section
and 101b sees a piece of its own side.  Each pair is therefore tested from both
corridors and taken if either agrees.  Surfaces already claimed by rule 1 or 2
are left alone.

Two cross-sections in the SAME plane, open to rooms on DIFFERENT storeys, are
rejected outright.  101c is two stories tall and ends against office 107 below
and IT room 116 above; if both were open a person would step out of 116 into
the void over the corridor.  In real construction the upper one is a guardrail
over a wall below, or there is no upper opening at all -- either way it is a
special case, so neither is assigned and both are named in the report.  If the
upper one really is a guardrail, the way to say so already exists: label that
upper room a mezzanine and rule 2 takes its edge.

Note this applies only ACROSS the run.  A long side open at two storeys is an
ordinary double-height edge, which is exactly what rule 4 relies on.

What no rule can settle: a corridor that dead-ends into a room on one storey
looks exactly like one that opens into a lobby.  Pairs whose far side is not
itself circulation or open floor are selected and then called out by name for
review.  Only the engineer can separate them, and --corridor-exclude drops the
ones that are really walls.


Open stairs
-----------

A stair is a corridor stood on end, and it inherits the corridor problem in a
sharper form.  101d's stair is 5.75 x 1.58 m, stacked over two storeys:

                     x = 6.05          long sides          x = 11.80
    Level 1 Stair    -> 101a Hallway   -> Lobby, 108 Conf   -> Lobby
    Level 2 Stair 2  -> 113 Mezzanine  -> Lobby, 113 Mezz   -> Lobby

The SIDES are unambiguous: a stair open along its length to a double-height
lobby has a guardrail there whichever way the flight runs, so those are taken
wherever the far side spans storeys or is a mezzanine.  (The side onto 108
Conference is not -- an ordinary room on one storey, so an ordinary wall.)

The ENDS are not derivable at all.  You step onto the flight at the bottom and
off it at the top, and those are opposite ends, so on each storey exactly one
end is open and the other is the wall behind the flight.  Which one is drawn as
a direction arrow, and the exported plan carries no arrows.  So the ends are
listed and left alone; --open-surface names the ones you have decided are
open, which keeps the decision in the command rather than in a hand edit.

Labelling the room "Open Stair" is the entire opt-in.  A plain "Stair" is
assumed enclosed, which is the safe reading -- a fire-rated stair with a
self-closing door is the common case, and an air boundary there would be wrong
in a way the results would not obviously show.


The engineer's overrides
------------------------

Two things a floor plan does not record, and no rule can therefore reach:

    --open-surface   these interior surfaces are open, whatever the rules say
    --solid-surface  these are real construction, overriding any rule

--solid-surface is for a wall the geometry cannot distinguish from a guardrail
because the difference is its fire rating: 205 Mezzanine reads as an open edge
onto the lobby and onto 101c, and is in fact a rated separation.
--open-surface is for the opposite -- a stair end, a doorway held open by
design.  Both are matched on either face, since an air boundary is a property
of the pair and half of one would mean nothing.

A promoted surface joins the construction already covering its space pair
rather than starting a second one.  That is not tidiness: EnergyPlus creates
mixing per Construction:AirBoundary, so two constructions between one pair of
zones would double the flow, and nothing in the model or the results would say
so.  There is a test for it.

Both are held by surface NAME, and surface names belong to OpenStudio, not to
this bridge -- nothing here ever calls setName on a surface.  A full rebuild
therefore reassigns them all, and a few land differently every time: two builds
of the BYTE-IDENTICAL floorplan JSON differed on 8 of 314 names, and one of
those, Surface 263, was a stair opening in one build and an office/store
partition in the other.  The churn sits in the fragments intersectSurfaces
makes when it splits a wall; most names are stable, which is what makes this
dangerous rather than obvious.

So re-read both lists off the report after a full build_osm_geometry.py, and do
not assume unchanged input gives unchanged names.  update_osm_geometry.py
--apply is safe: it rebuilds only the spaces whose vertex hash moved, and
nudging one vertex of 102 Office changed 5 surfaces, every one keeping its
space, its partner and its name.

Forgetting to re-read them is not hypothetical, and it fails silently: after
the roof rebuild the 205 Mezzanine report was regenerated without
--solid-surface, rule 2 duly proposed the rated wall onto the lobby and onto
101c as guardrail edges, and applying the report opened 20.3 m2 of fire
separation.  Nothing in the model objected.  The backstop is
tests/test_air_boundary_sizing.py, whose applied-model checks assert that wall
is still solid -- keyed on the space pair, so a renumbering cannot make the
check quietly pass by pointing it at different geometry.  Run the suite after
applying a report.

Keyed on the single surface, deliberately, rather than on the space pair.  A
pair can share many surfaces -- 113 Mezzanine to the lobby has six -- and they
need not all be the same kind of thing; and naming one surface asks less of the
engineer than working out what it is matched to.
"""

import argparse
import json
import math
import os
import re
import sys

import openstudio

# Rooms whose shared wall with a multi-story space is a guardrail.  Matched
# against the room name from the floor plan, case-insensitively.
MEZZANINE_PATTERN = r"mezzanine|balcony|gallery|catwalk"

# Rooms whose cross-section is an opening rather than a wall.  Matched against
# the room name from the floor plan, case-insensitively.
CORRIDOR_PATTERN = r"corridor|hallway|\bhall\b|passage|circulation|breezeway"

# Used only to decide which selected pairs get called out for review, never to
# select or reject one.  A corridor ending in a lobby or another corridor is an
# unambiguous open transition; one ending in an office is not, and no geometry
# distinguishes the two.
OPEN_SPACE_PATTERN = r"lobby|atrium|vestibule|concourse|open\s*(work|plan|office)"

# A stair the engineer has declared open.  A plain "Stair" gets nothing from
# rule 4: a stair is a quasi-corridor with an opening at ONE end per storey and
# a wall at the other, and which end is which is drawn as an arrow the bridge
# cannot read.  Labelling it "Open Stair" opts its *sides* in; the ends stay
# the engineer's call.
OPEN_STAIR_PATTERN = r"open\s*stair"

# A wall no wider than a quarter of the corridor's run counts as "narrow in
# comparison to the length of the hallway".
DEFAULT_CORRIDOR_NARROW_RATIO = 0.25
# It must also span the corridor's own width, within this fraction, to be a
# slice through the corridor rather than a fragment of its side.
DEFAULT_CORRIDOR_SPAN_TOL = 0.15
# And stand square to the run: |cos| between the wall's plan direction and the
# corridor's long axis, so 0.30 allows about 17 degrees out of square.
DEFAULT_CORRIDOR_SQUARE_COS = 0.30

G = 9.80665                 # m/s2
# dT across an *open* boundary is self-limiting, not a free parameter: the
# exchange this file computes is the mechanism that holds the two zones
# together, so they equilibrate. 0.5 K is the accepted working figure. A large
# dT and an open boundary are mutually exclusive -- 10 K between adjacent
# commercial zones means an enclosure (cold store, sauna), which would not have
# an open boundary at all. --delta-t exists for an engineer's judgement on a
# genuine edge case, not for exploring a range.
DEFAULT_DELTA_T = 0.5       # K, temperature difference across the opening
DEFAULT_T_MEAN = 293.15     # K, mean absolute air temperature
# IEA Annex 20 Subtask 2 (van der Maas 1992) measured 0.43 from steady-state
# doorway experiments, "in agreement with reference experiments used by
# ASHRAE"; the reported spread across studies is 0.35-0.63.  The textbook 0.6
# sits at the top of that and its own Fig. 2.18 notes "measured doorway
# velocities in air were generally smaller than the calculated parabolic
# profile using a discharge coefficient of 0.6".
CD_VERTICAL = 0.43          # discharge coefficient, measured
C_HORIZONTAL = 0.055        # Epstein thin-partition coefficient, L/D < 0.15

# Annex 20 Fig. 2.16: Scott et al. had to shrink the aperture width ratio
# below Aw = 0.1 to "block" the boundary-layer flow and drive the two zones to
# different temperatures at all.  Above it the flow is boundary-layer driven,
# not bulk-density driven -- the regime Brown & Solvason describes -- and the
# isothermality factor dT/dTw collapses towards zero.  Past this ratio the
# correlation below is extrapolation, and the report says so.
AW_DENSITY_DRIVEN_MAX = 0.1

# EnergyPlus's own default, for comparison in the report.
EPLUS_DEFAULT_ACH = 0.5

# An air boundary has to do two jobs, and they pull in opposite directions:
# couple the zones at steady state, AND stay loose enough that a transient can
# briefly override the coupling and be visible in the results.  The sized rate
# does the first well and the second not at all -- at 45 ACH a solar gain
# landing on a mezzanine is absorbed into the space below within the timestep
# and never appears.  That excursion cannot be computed in advance; it is what
# the simulation is for.  So the rate is capped to leave room for it.
#
# 5 ACH still couples an ordinary imbalance tightly (~100 W across a 79 m3
# mezzanine settles at 0.75 K) while letting a real excursion show.  A large
# sustained split in the results is then a finding about the design, which is
# the model earning its keep.
DEFAULT_MAX_ACH = 5.0


def load_model(path):
    loaded = openstudio.osversion.VersionTranslator().loadModel(
        openstudio.path(path))
    if not loaded.is_initialized():
        raise SystemExit("could not load %s" % path)
    return loaded.get()


def plan_index(plan):
    """{space_id: (story_spec, space_spec, built_height_m)}."""
    out = {}
    for story in plan["stories"]:
        for space in story["spaces"]:
            height = float(space.get("height_m") or story["floor_to_floor_m"])
            out[space["id"]] = (story, space, height)
    return out


def shaft_pairs(index):
    """Space-id pairs sharing a footprint across stories.

    Keyed on the vertex set rather than the ordered loop, so the same room
    traced from a different starting corner still matches -- the same key the
    exporter reports its cross-story matches on.
    """
    seen = {}
    for space_id, (story, space, _h) in index.items():
        key = tuple(sorted(tuple(v) for v in space["vertices"]))
        seen.setdefault(key, []).append((story["name"], space_id))

    pairs = []
    for group in seen.values():
        if len(group) < 2:
            continue
        for i in range(len(group)):
            for j in range(i + 1, len(group)):
                if group[i][0] != group[j][0]:      # different stories only
                    pairs.append((group[i][1], group[j][1]))
    return pairs


def convex_hull(points):
    """Monotone-chain hull of (x, y) tuples."""
    pts = sorted(set(points))
    if len(pts) < 3:
        return pts

    def half(seq):
        out = []
        for p in seq:
            while len(out) >= 2:
                (ax, ay), (bx, by) = out[-2], out[-1]
                if (bx - ax) * (p[1] - ay) - (by - ay) * (p[0] - ax) <= 0:
                    out.pop()
                else:
                    break
            out.append(p)
        return out

    return half(pts)[:-1] + half(pts[::-1])[:-1]


def footprint_axes(vertices):
    """(length, width, unit long axis) of the minimum-area bounding rectangle.

    A corridor's length has to survive the building not being axis-aligned --
    this one is drawn on a 45 degree north axis -- so it is measured on the
    footprint's own principal axes rather than on x and y.  The minimum-area
    rectangle is exact for the rectangular corridors this rule is about, and
    degrades sensibly for an L-shaped one.
    """
    hull = convex_hull([(round(v[0], 6), round(v[1], 6)) for v in vertices])
    best = None
    for i in range(len(hull)):
        ax, ay = hull[i]
        bx, by = hull[(i + 1) % len(hull)]
        norm = math.hypot(bx - ax, by - ay)
        if norm < 1e-9:
            continue
        ux, uy = (bx - ax) / norm, (by - ay) / norm
        along = [p[0] * ux + p[1] * uy for p in hull]
        across = [-p[0] * uy + p[1] * ux for p in hull]
        a = max(along) - min(along)
        b = max(across) - min(across)
        if best is not None and a * b >= best[0]:
            continue
        best = ((a * b, a, b, (ux, uy)) if a >= b
                else (a * b, b, a, (-uy, ux)))
    if best is None:
        return 0.0, 0.0, (1.0, 0.0)
    return best[1], best[2], best[3]


def wall_plan_run(surface):
    """(width, unit plan direction) of a vertical surface, seen from above.

    The direction comes off the bounding box, so its sign is arbitrary -- which
    is harmless here, because it is only ever used inside an absolute value.
    """
    xs = [p.x() for p in surface.vertices()]
    ys = [p.y() for p in surface.vertices()]
    dx, dy = max(xs) - min(xs), max(ys) - min(ys)
    run = math.hypot(dx, dy)
    if run < 1e-9:
        return 0.0, (1.0, 0.0)
    return run, (dx / run, dy / run)


def plane_key(surface):
    """Canonical (nx, ny, offset) of a vertical surface's line in plan.

    Sign-normalised, so two walls lying in one plane key the same whichever
    way they face -- the surfaces being compared belong to different spaces
    (a corridor's two ends, a stair's two storeys) and their outward normals
    need not agree.
    """
    normal = surface.outwardNormal()
    nx, ny = normal.x(), normal.y()
    norm = math.hypot(nx, ny)
    if norm < 1e-9:                     # horizontal: no plan line
        return None
    nx, ny = nx / norm, ny / norm
    if nx < -1e-9 or (abs(nx) <= 1e-9 and ny < 0):
        nx, ny = -nx, -ny
    pts = surface.vertices()
    offset = sum(p.x() * nx + p.y() * ny for p in pts) / len(pts)
    return (round(nx, 3), round(ny, 3), round(offset, 3))


def surface_height(surface):
    """Vertical extent of a surface, metres."""
    zs = [p.z() for p in surface.vertices()]
    return max(zs) - min(zs)


def vertical_flow(width, height, delta_t, t_mean):
    """One-way buoyancy exchange through a vertical opening, m3/s."""
    if width <= 0 or height <= 0:
        return 0.0
    return ((CD_VERTICAL / 3.0) * width * height ** 1.5
            * math.sqrt(G * delta_t / t_mean))


def horizontal_flow(area, delta_t, t_mean):
    """One-way buoyancy exchange through a horizontal opening, m3/s."""
    if area <= 0:
        return 0.0
    diameter = math.sqrt(4.0 * area / math.pi)
    return C_HORIZONTAL * math.sqrt((G * delta_t / t_mean) * diameter ** 5)


def find(model, plan, fcmap, pattern, corridor=None, open_stair=None,
         declared=None):
    """Openings needing an air boundary, as flat records.

    `corridor` is the rule-3 configuration -- pattern, narrow_ratio, span_tol,
    square_cos, exclude -- and `open_stair` the rule-4 one; either may be None
    to skip that rule.  Returns the openings, warnings, room numbers, and an
    `attention` dict of things a threshold cannot settle.
    """
    index = plan_index(plan)
    spaces = {s.nameString(): s for s in model.getSpaces()}
    room_number = {}
    for space_id, entry in fcmap.items():
        room_number[entry["space_name"]] = entry.get("room_number") or ""

    def named(space_id):
        entry = fcmap.get(space_id)
        return spaces.get(entry["space_name"]) if entry else None

    openings, warnings = [], []

    # --- rule 1: shafts -----------------------------------------------------
    for lower_id, upper_id in shaft_pairs(index):
        a, b = named(lower_id), named(upper_id)
        if a is None or b is None:
            continue
        if index[lower_id][0]["elevation_m"] > index[upper_id][0]["elevation_m"]:
            a, b = b, a
        hits = 0
        for surface in a.surfaces():
            if surface.surfaceType() not in ("Floor", "RoofCeiling"):
                continue
            adjacent = surface.adjacentSurface()
            if not adjacent.is_initialized():
                continue
            partner = adjacent.get()
            space = partner.space()
            if not space.is_initialized():
                continue
            if space.get().nameString() != b.nameString():
                continue
            openings.append({
                "kind": "shaft",
                "orientation": "horizontal",
                "space_a": a.nameString(), "space_b": b.nameString(),
                "surface_a": surface.nameString(),
                "surface_b": partner.nameString(),
                "area_m2": surface.grossArea(),
                "height_m": None,
            })
            hits += 1
        if not hits:
            warnings.append(
                "%s / %s share a footprint but no interior floor-ceiling pair "
                "joins them -- are they stacked?"
                % (a.nameString(), b.nameString()))

    # --- rule 2: mezzanine edges -------------------------------------------
    tall = set()
    for space_id, (story, _space, height) in index.items():
        if height > story["floor_to_floor_m"] + 1e-6:
            entry = fcmap.get(space_id)
            if entry:
                tall.add(entry["space_name"])

    for space_id, (_story, space, _h) in index.items():
        if not pattern.search(space["name"]):
            continue
        mezz = named(space_id)
        if mezz is None:
            continue
        for surface in mezz.surfaces():
            if surface.surfaceType() != "Wall":
                continue
            adjacent = surface.adjacentSurface()
            if not adjacent.is_initialized():
                continue
            partner = adjacent.get()
            other = partner.space()
            if not other.is_initialized():
                continue
            other_name = other.get().nameString()
            if other_name not in tall:
                continue
            openings.append({
                "kind": "mezzanine",
                "orientation": "vertical",
                "space_a": mezz.nameString(), "space_b": other_name,
                "surface_a": surface.nameString(),
                "surface_b": partner.nameString(),
                "area_m2": surface.grossArea(),
                "height_m": surface_height(surface),
            })

    # --- rule 3: corridor cross-sections -----------------------------------
    attention = {"corridor_rejected": [], "open_stair_ends": [],
                 "declared_open": [], "declared_solid": []}
    if corridor:
        found, rejected = corridor_openings(index, fcmap, named, openings,
                                            corridor)
        openings += found
        attention["corridor_rejected"] = rejected

    # --- rule 4: open stair edges ------------------------------------------
    if open_stair:
        found, ends = open_stair_openings(index, fcmap, named, openings, tall,
                                          pattern, open_stair)
        openings += found
        attention["open_stair_ends"] = ends

    # --- the engineer's overrides, last, so they beat every rule ------------
    declared = declared or {}
    if declared.get("open"):
        found, problems = promote_declared(model, openings, declared["open"])
        openings += found
        attention["declared_open"] = found
        warnings += problems
        # An end promoted by name is no longer an open question.
        promoted = {op["surface_a"] for op in found}
        attention["open_stair_ends"] = [
            op for op in attention["open_stair_ends"]
            if op["surface_a"] not in promoted]
    if declared.get("solid"):
        openings, dropped = drop_solid(openings, declared["solid"])
        attention["declared_solid"] = dropped
        named_solid = {op["surface_a"] for op in dropped}
        named_solid |= {op["surface_b"] for op in dropped}
        for missing in sorted(declared["solid"] - named_solid):
            warnings.append("--solid-surface %s: no rule had selected it, so "
                            "nothing changed" % missing)

    return openings, warnings, room_number, attention


def story_lookup(fcmap):
    """{openstudio space name: story name}."""
    return {e["space_name"]: e.get("story", "") for e in fcmap.values()}


def claimed_surfaces(openings):
    """Surfaces an earlier rule has already taken -- one surface, one
    construction."""
    claimed = set()
    for op in openings:
        claimed.add(op["surface_a"])
        claimed.add(op["surface_b"])
    return claimed


def reject_stacked_cross_sections(candidates, story_of):
    """Split cross-sections into (kept, rejected) on the two-storey test.

    Two openings that lie in the SAME plane, both cutting across the run, and
    open to rooms on DIFFERENT storeys cannot both be open: something has to
    stop a person walking out of the upper room into the void.  In real
    construction the upper one is a guardrail over a wall below, or there is
    no upper opening at all -- either way it is a special case, so both are
    rejected and reported rather than guessed at.

    Note this applies only ACROSS the run.  A long side open at two storeys is
    just a double-height edge and is perfectly ordinary; rule 4 relies on that.
    """
    planes = {}
    for cand in candidates:
        planes.setdefault(cand["plane"], []).append(cand)

    kept, rejected = [], []
    for group in planes.values():
        stories = {story_of.get(c["space_b"], "") for c in group}
        if len(group) > 1 and len(stories) > 1:
            rejected.extend(group)
        else:
            kept.extend(group)
    return kept, rejected


def corridor_openings(index, fcmap, named, claimed_by, cfg):
    """Walls that slice a corridor square across its run.

    Three conditions, all necessary -- see "Corridors" in the module docstring
    for the measurements that show why the first alone is not enough:

      narrow  the wall is short compared with the corridor's length;
      span    it covers the corridor's own width, so it is a full cross-section
              and not a fragment of the flank;
      square  it stands across the run rather than along it.
    """
    open_pattern = re.compile(OPEN_SPACE_PATTERN, re.IGNORECASE)
    room_name = {}
    for space_id, (_story, space, _h) in index.items():
        entry = fcmap.get(space_id)
        if entry:
            room_name[entry["space_name"]] = space["name"]
    story_of = story_lookup(fcmap)

    # Rules 1 and 2 have first claim: a mezzanine edge that happens to sit
    # across a corridor is already sized as a guardrail, and one surface can
    # only carry one construction.
    claimed = claimed_surfaces(claimed_by)

    found, rejected = [], []
    for space_id, (_story, space, _h) in index.items():
        if not cfg["pattern"].search(space["name"]):
            continue
        corridor = named(space_id)
        if corridor is None:
            continue
        length, width, axis = footprint_axes(space["vertices"])
        if length <= 0 or width <= 0:
            continue

        candidates = []
        for surface in corridor.surfaces():
            if surface.surfaceType() != "Wall":
                continue
            adjacent = surface.adjacentSurface()
            if not adjacent.is_initialized():
                continue
            partner = adjacent.get()
            other = partner.space()
            if not other.is_initialized():
                continue
            if surface.nameString() in claimed or partner.nameString() in claimed:
                continue

            run, direction = wall_plan_run(surface)
            if run <= 0:
                continue
            narrow = run / length
            span = run / width
            square = abs(direction[0] * axis[0] + direction[1] * axis[1])
            if (narrow > cfg["narrow_ratio"]
                    or abs(span - 1.0) > cfg["span_tol"]
                    or square > cfg["square_cos"]):
                continue

            other_name = other.get().nameString()
            if cfg["exclude"] and cfg["exclude"].search(
                    "%s|%s" % (corridor.nameString(), other_name)):
                continue

            far = room_name.get(other_name, "")
            candidates.append({
                "kind": "corridor",
                "orientation": "vertical",
                "space_a": corridor.nameString(), "space_b": other_name,
                "surface_a": surface.nameString(),
                "surface_b": partner.nameString(),
                "area_m2": surface.grossArea(),
                "height_m": surface_height(surface),
                "narrow_ratio": narrow,
                "span_ratio": span,
                "plane": plane_key(surface),
                "z_range": (min(p.z() for p in surface.vertices()),
                            max(p.z() for p in surface.vertices())),
                # False means the far side is an enclosed room, so the wall may
                # be a real one. The geometry cannot tell; the report asks.
                "partner_open": bool(cfg["pattern"].search(far)
                                     or open_pattern.search(far)),
            })
            # Claim as we go, so the same pair is not re-found from the other
            # corridor of an L-junction.  Rejected candidates are claimed too:
            # a surface this rule has ruled out must stay ruled out.
            claimed.add(surface.nameString())
            claimed.add(partner.nameString())

        kept, dropped = reject_stacked_cross_sections(candidates, story_of)
        found.extend(kept)
        rejected.extend(dropped)

    return found, rejected


def open_stair_openings(index, fcmap, named, claimed_by, tall, mezz_pattern,
                        cfg):
    """Guardrail edges of a stair the engineer has labelled open.

    A stair is a corridor stood on end, and it inherits the corridor problem in
    a sharper form: on each storey exactly one end is the way in and the other
    is the wall behind the flight, and which is which is drawn as a direction
    arrow that the exported plan does not carry.  So the two are split:

      * the SIDES -- walls along the run, onto a space that spans storeys or
        onto a mezzanine -- are guardrail edges, and are taken automatically;
      * the ENDS -- walls across the run -- are reported and left alone.

    Labelling the room "Open Stair" is the whole opt-in.  A plain "Stair" is
    assumed enclosed, which is the safe reading: a fire-rated stair with a
    self-closing door is the common case, and an air boundary there would be
    wrong in a way the results would not obviously show.
    """
    claimed = claimed_surfaces(claimed_by)
    story_of = story_lookup(fcmap)
    room_name = {}
    for space_id, (_story, space, _h) in index.items():
        entry = fcmap.get(space_id)
        if entry:
            room_name[entry["space_name"]] = space["name"]

    found, ends = [], []
    for space_id, (_story, space, _h) in index.items():
        if not cfg["pattern"].search(space["name"]):
            continue
        stair = named(space_id)
        if stair is None:
            continue
        length, width, axis = footprint_axes(space["vertices"])
        if length <= 0 or width <= 0:
            continue

        for surface in stair.surfaces():
            if surface.surfaceType() != "Wall":
                continue
            adjacent = surface.adjacentSurface()
            if not adjacent.is_initialized():
                continue
            partner = adjacent.get()
            other = partner.space()
            if not other.is_initialized():
                continue
            if surface.nameString() in claimed or partner.nameString() in claimed:
                continue

            other_name = other.get().nameString()
            far = room_name.get(other_name, "")
            # The two things an open stair can legitimately open onto.
            if not (other_name in tall or mezz_pattern.search(far)):
                continue

            run, direction = wall_plan_run(surface)
            if run <= 0:
                continue
            square = abs(direction[0] * axis[0] + direction[1] * axis[1])
            across = (abs(run / width - 1.0) <= cfg["span_tol"]
                      and square <= cfg["square_cos"])

            record = {
                "kind": "open_stair",
                "orientation": "vertical",
                "space_a": stair.nameString(), "space_b": other_name,
                "surface_a": surface.nameString(),
                "surface_b": partner.nameString(),
                "area_m2": surface.grossArea(),
                "height_m": surface_height(surface),
                "plane": plane_key(surface),
                "run_m": run,
                "partner_story": story_of.get(other_name, ""),
            }
            if across:
                # One end per storey is the way in and the other is a wall.
                # Nothing in the plan says which, so neither is taken here --
                # --open-surface promotes the ones you decide are open.
                ends.append(record)
                continue
            found.append(record)
            claimed.add(surface.nameString())
            claimed.add(partner.nameString())

    return found, ends


def promote_declared(model, openings, names):
    """Interior surfaces the engineer has declared open, whatever the rules say.

    Some openings are not derivable from a floor plan at all -- which end of a
    stair the flight arrives at, a doorway held open by design.  This is where
    that judgement is recorded so the run reproduces.

    A promoted surface joins the construction of any opening already covering
    the same pair of spaces, rather than making a second one.  Two air-boundary
    constructions between one pair of zones would give EnergyPlus two mixing
    objects and double the flow, so this is not a cosmetic detail.
    """
    by_name = {s.nameString(): s for s in model.getSurfaces()}
    claimed = claimed_surfaces(openings)
    # Existing pair -> how an opening between those two spaces is labelled.
    existing = {}
    for op in openings:
        existing.setdefault(frozenset((op["space_a"], op["space_b"])),
                            (op["kind"], op["space_a"], op["space_b"]))

    found, problems = [], []
    for name in sorted(names):
        surface = by_name.get(name)
        if surface is None:
            problems.append("--open-surface %s: no such surface" % name)
            continue
        if name in claimed:
            continue                    # a rule already took it
        adjacent = surface.adjacentSurface()
        if not adjacent.is_initialized():
            problems.append("--open-surface %s: not an interior surface "
                            "(boundary %s)"
                            % (name, surface.outsideBoundaryCondition()))
            continue
        partner = adjacent.get()
        if not (surface.space().is_initialized()
                and partner.space().is_initialized()):
            continue
        mine = surface.space().get().nameString()
        theirs = partner.space().get().nameString()
        pair = frozenset((mine, theirs))
        kind, space_a, space_b = existing.get(pair, ("declared", mine, theirs))
        # Two declared surfaces can share a pair neither rule nor an earlier
        # declaration already covers -- the second one has to see the first's
        # choice of kind/space_a/space_b, or it mints its own and group_pairs
        # (keyed on that exact triple) gives the pair two constructions.
        existing.setdefault(pair, (kind, space_a, space_b))
        vertical = surface.surfaceType() == "Wall"
        found.append({
            "kind": kind,
            "orientation": "vertical" if vertical else "horizontal",
            "space_a": space_a, "space_b": space_b,
            "surface_a": surface.nameString(),
            "surface_b": partner.nameString(),
            "area_m2": surface.grossArea(),
            "height_m": surface_height(surface) if vertical else None,
            "declared": True,
        })
        claimed.add(name)
        claimed.add(partner.nameString())
    return found, problems


def drop_solid(openings, names):
    """Openings the engineer has declared solid -- a fire wall, a rated
    separation.

    Matched on either face, so naming one side is enough: an air boundary is a
    property of the pair, and half of one would be meaningless.
    """
    kept, dropped = [], []
    for op in openings:
        if op["surface_a"] in names or op["surface_b"] in names:
            dropped.append(op)
        else:
            kept.append(op)
    return kept, dropped


def group_pairs(model, openings, room_number, delta_t, t_mean):
    """Openings collapsed to one entry per space pair, with a sized ACH."""
    volume = {s.nameString(): s.volume() for s in model.getSpaces()}
    story_of = {
        s.nameString(): (s.buildingStory().get().nameString()
                         if s.buildingStory().is_initialized() else "")
        for s in model.getSpaces()}
    wall_areas = {
        s.nameString(): sum(f.grossArea() for f in s.surfaces()
                            if f.surfaceType() == "Wall")
        for s in model.getSpaces()}

    groups = {}
    for op in openings:
        key = (op["kind"], op["space_a"], op["space_b"])
        groups.setdefault(key, []).append(op)

    results = []
    for (kind, space_a, space_b), ops in groups.items():
        flow = 0.0
        for op in ops:
            if op["orientation"] == "vertical":
                height = op["height_m"] or 0.0
                # Effective width, so a non-rectangular opening still gets its
                # true area at its true height.
                width = op["area_m2"] / height if height > 0 else 0.0
                flow += vertical_flow(width, height, delta_t, t_mean)
            else:
                flow += horizontal_flow(op["area_m2"], delta_t, t_mean)

        v_a, v_b = volume.get(space_a, 0.0), volume.get(space_b, 0.0)
        v_small = min(v_a, v_b)

        # Annex 20's aperture width ratio, Aw = W / Wr: how much of the
        # smaller zone's perimeter is open.  Areas divided by a common height
        # give the same ratio as widths, so this is Aw directly.
        smaller = space_a if v_a <= v_b else space_b
        wall_area = wall_areas.get(smaller, 0.0)
        aw = (sum(o["area_m2"] for o in ops) / wall_area) if wall_area else 0.0
        ach = (flow * 3600.0 / v_small) if v_small > 0 else 0.0

        num_a = room_number.get(space_a, "") or space_a
        num_b = room_number.get(space_b, "") or space_b
        if kind == "shaft":
            label = num_a if num_a == num_b else "%s-%s" % (num_a, num_b)
            name = "Air Boundary - Shaft %s" % label
        elif kind == "corridor":
            name = "Air Boundary - Corridor %s to %s" % (num_a, num_b)
        elif kind == "open_stair":
            name = "Air Boundary - Open Stair %s to %s" % (num_a, num_b)
        elif kind == "declared":
            label = num_a if num_a == num_b else "%s to %s" % (num_a, num_b)
            name = "Air Boundary - Opening %s" % label
        else:
            name = "Air Boundary - Mezzanine %s to %s" % (num_a, num_b)

        area = sum(o["area_m2"] for o in ops)
        results.append({
            "construction_name": name,
            # Half the opening carries flow each way, so this is the mean
            # interfacial speed -- the quickest check that a rate is sane.
            "velocity_m_s": (flow / (area / 2.0)) if area > 0 else 0.0,
            "kind": kind,
            "space_a": space_a, "space_b": space_b,
            "openings": len(ops),
            "area_m2": area,
            "flow_m3_s": flow,
            "volume_smaller_m3": v_small,
            "smaller_space": smaller,
            "aperture_width_ratio": aw,
            # Rule 3 only. False = the far side is an enclosed room, so the
            # report asks the engineer to confirm this is really an opening.
            "partner_open": all(o.get("partner_open", True) for o in ops),
            "narrow_ratio": max([o["narrow_ratio"] for o in ops]
                                if kind == "corridor" else [0.0]),
            "span_ratio": max([o["span_ratio"] for o in ops]
                              if kind == "corridor" else [0.0]),
            # A fixed ZoneMixing rate is linear in dT, unlike the buoyancy it
            # stands in for, so the dT a 1 kW imbalance produces is simply
            # W / (rho.cp.Q) -- and it rises in proportion to any cap applied.
            "delta_t_at_1kw": (1000.0 / (1.2 * 1006.0 * flow)) if flow else 0.0,
            "recommended_ach": ach,
            "surface_names": sorted(
                [o["surface_a"] for o in ops] + [o["surface_b"] for o in ops],
                key=lambda n: (re.sub(r"\d+$", "", n),
                               int(re.search(r"\d+$", n).group())
                               if re.search(r"\d+$", n) else 0)),
        })

    # Room numbers are not unique across stories -- a stair is "101d" on both
    # -- so two genuinely different space pairs can land on one construction
    # name.  Applying both would silently merge them into one construction, so
    # collisions are broken by the story of the first space.
    counts = {}
    for r in results:
        counts[r["construction_name"]] = counts.get(r["construction_name"],
                                                    0) + 1
    for r in results:
        if counts[r["construction_name"]] > 1:
            story = story_of.get(r["space_a"], "")
            if story:
                r["construction_name"] = "%s - %s" % (r["construction_name"],
                                                      story)
    seen = {}
    for r in results:
        name = r["construction_name"]
        if name in seen:
            seen[name] += 1
            r["construction_name"] = "%s %d" % (name, seen[name])
        else:
            seen[name] = 1

    results.sort(key=lambda r: (r["kind"], -r["recommended_ach"]))
    return results


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("osm")
    ap.add_argument("floorplan")
    ap.add_argument("--fcmap", help="defaults to <osm>.fcmap.json")
    ap.add_argument("--mezzanine-pattern", default=MEZZANINE_PATTERN,
                    help="regex matched against the room name (default %r)"
                         % MEZZANINE_PATTERN)
    ap.add_argument("--corridor-pattern", default=CORRIDOR_PATTERN,
                    help="regex matched against the room name (default %r)"
                         % CORRIDOR_PATTERN)
    ap.add_argument("--corridor-narrow-ratio", type=float,
                    default=DEFAULT_CORRIDOR_NARROW_RATIO,
                    help="wall width / corridor length below which the wall "
                         "counts as narrow (default %.2f)"
                         % DEFAULT_CORRIDOR_NARROW_RATIO)
    ap.add_argument("--corridor-span-tol", type=float,
                    default=DEFAULT_CORRIDOR_SPAN_TOL,
                    help="how far wall width / corridor width may sit from 1 "
                         "and still be a full cross-section (default %.2f)"
                         % DEFAULT_CORRIDOR_SPAN_TOL)
    ap.add_argument("--corridor-square-cos", type=float,
                    default=DEFAULT_CORRIDOR_SQUARE_COS,
                    help="|cos| between the wall and the corridor's run, "
                         "below which it stands square (default %.2f)"
                         % DEFAULT_CORRIDOR_SQUARE_COS)
    ap.add_argument("--corridor-exclude", default=None,
                    help="regex on 'space_a|space_b'; drops a corridor pair "
                         "the geometry cannot tell from a real wall")
    ap.add_argument("--no-corridors", action="store_true",
                    help="skip rule 3 entirely")
    ap.add_argument("--open-stair-pattern", default=OPEN_STAIR_PATTERN,
                    help="regex matched against the room name (default %r). "
                         "A plain 'Stair' is assumed enclosed."
                         % OPEN_STAIR_PATTERN)
    ap.add_argument("--open-surface", default=None,
                    help="comma-separated surface names you have decided are "
                         "open, whatever the rules say -- a stair end, a "
                         "doorway held open by design. Joins the construction "
                         "of any opening already covering the same space pair.")
    ap.add_argument("--solid-surface", default=None,
                    help="comma-separated surface names that are real "
                         "construction -- a fire wall, a rated separation -- "
                         "overriding any rule that selected them. Naming "
                         "either face is enough.")
    ap.add_argument("--no-open-stairs", action="store_true",
                    help="skip rule 4 entirely")
    ap.add_argument("--delta-t", type=float, default=DEFAULT_DELTA_T,
                    help="temperature difference across the opening, K "
                         "(default %.1f)" % DEFAULT_DELTA_T)
    ap.add_argument("--t-mean", type=float, default=DEFAULT_T_MEAN,
                    help="mean absolute air temperature, K (default %.2f)"
                         % DEFAULT_T_MEAN)
    ap.add_argument("--max-ach", type=float, default=DEFAULT_MAX_ACH,
                    help="cap the sized rate (default %.1f). The headroom is "
                         "deliberate: it lets a transient override the "
                         "coupling and reach the results. 0 disables the cap."
                         % DEFAULT_MAX_ACH)
    ap.add_argument("--apply-json", action="store_true",
                    help="emit the arguments apply_air_boundaries.py takes, "
                         "as JSON on stdout")
    ap.add_argument("--out",
                    help="with --apply-json, write the JSON here as UTF-8 "
                         "instead of to stdout -- safer than a shell redirect")
    args = ap.parse_args()

    # OpenStudio's C++ logger writes to stdout, not stderr, so a model that
    # needs colinear points added to a polyhedron prints two dozen lines right
    # where the JSON is supposed to start.  --apply-json promises something
    # pipeable, so on that path the logger is silenced and stdout carries the
    # report and nothing else.  2>/dev/null does not help: the noise was never
    # on stderr to begin with.
    # Raising the level rather than calling disable(): disabling detaches the
    # sink, and boost's own default sink then takes over and prints *more*,
    # at Info, with timestamps.  Measured, not guessed.
    if args.apply_json:
        openstudio.Logger.instance().standardOutLogger().setLogLevel(
            openstudio.Fatal)

    if args.delta_t <= 0:
        sys.exit("--delta-t must be greater than 0; a zero temperature "
                 "difference drives no buoyancy flow at all.")

    # dT is an interval and is quite properly typed in K, which gives anyone
    # reaching for --t-mean every reason to type 20 as well.  That would be
    # accepted silently and inflate every rate by sqrt(293/20).
    if args.t_mean < 200.0:
        sys.exit("--t-mean is an ABSOLUTE temperature in kelvin; %.1f looks "
                 "like Celsius.\n%.0f C is %.2f K. Passing Celsius here "
                 "inflates every rate by sqrt(%.0f/%.0f) = %.1fx."
                 % (args.t_mean, args.t_mean, args.t_mean + 273.15,
                    DEFAULT_T_MEAN, args.t_mean,
                    (DEFAULT_T_MEAN / args.t_mean) ** 0.5))

    osm = os.path.abspath(args.osm)
    fcmap_path = args.fcmap or (os.path.splitext(osm)[0] + ".fcmap.json")
    with open(args.floorplan, encoding="utf-8") as fh:
        plan = json.load(fh)
    with open(fcmap_path, encoding="utf-8") as fh:
        fcmap = json.load(fh)["spaces"]

    model = load_model(osm)
    pattern = re.compile(args.mezzanine_pattern, re.IGNORECASE)
    corridor = None if args.no_corridors else {
        "pattern": re.compile(args.corridor_pattern, re.IGNORECASE),
        "narrow_ratio": args.corridor_narrow_ratio,
        "span_tol": args.corridor_span_tol,
        "square_cos": args.corridor_square_cos,
        "exclude": (re.compile(args.corridor_exclude, re.IGNORECASE)
                    if args.corridor_exclude else None),
    }
    open_stair = None if args.no_open_stairs else {
        "pattern": re.compile(args.open_stair_pattern, re.IGNORECASE),
        "span_tol": args.corridor_span_tol,
        "square_cos": args.corridor_square_cos,
    }
    declared = {
        "open": {n.strip() for n in (args.open_surface or "").split(",")
                 if n.strip()},
        "solid": {n.strip() for n in (args.solid_surface or "").split(",")
                  if n.strip()},
    }
    openings, warnings, room_number, attention = find(
        model, plan, fcmap, pattern, corridor, open_stair, declared)
    results = group_pairs(model, openings, room_number, args.delta_t,
                          args.t_mean)

    for r in results:
        r["uncapped_ach"] = r["recommended_ach"]
        r["uncapped_delta_t_at_1kw"] = r["delta_t_at_1kw"]
        r["capped"] = bool(args.max_ach > 0
                           and r["recommended_ach"] > args.max_ach)
        if r["capped"]:
            r["recommended_ach"] = args.max_ach
            # dT rises in exact proportion, because a fixed mixing rate is
            # linear in dT where the buoyancy it replaces is not.
            r["delta_t_at_1kw"] *= r["uncapped_ach"] / args.max_ach

    if args.apply_json:
        report = json.dumps([{
            "construction_name": r["construction_name"],
            "surface_names": ",".join(r["surface_names"]),
            "air_exchange_method": "SimpleMixing",
            "simple_mixing_ach": round(r["recommended_ach"], 2),
        } for r in results], indent=2)
        # --out rather than a redirect, because PowerShell's `>` writes UTF-16
        # and the reader opens the file as UTF-8.  That combination fails on
        # the very first byte, a long way from anything that looks like the
        # cause.  Piping has the same hazard; writing the file here has none.
        if args.out:
            with open(args.out, "w", encoding="utf-8") as handle:
                handle.write(report + "\n")
            print("wrote %s\n  %d construction(s), %d surface(s)"
                  % (os.path.abspath(args.out), len(results),
                     sum(len(r["surface_names"]) for r in results)),
                  file=sys.stderr)
        else:
            print(report)
        return 0

    total_surfaces = sum(len(r["surface_names"]) for r in results)
    print("%d space pair(s), %d surface(s)\n" % (len(results), total_surfaces))

    header = ("%-38s %8s %6s %9s %8s %8s %8s"
              % ("construction", "area m2", "Aw", "V_small", "sized",
                 "APPLIED", "dT@1kW"))
    print(header)
    print("-" * len(header))
    for r in results:
        print("%-38s %8.1f %6.2f%s %9.1f %8.1f %8.1f%s %7.2fK"
              % (r["construction_name"], r["area_m2"],
                 r["aperture_width_ratio"],
                 "*" if r["aperture_width_ratio"] > AW_DENSITY_DRIVEN_MAX
                 else " ",
                 r["volume_smaller_m3"], r["uncapped_ach"],
                 r["recommended_ach"], "c" if r["capped"] else " ",
                 r["delta_t_at_1kw"]))
    print()
    print("  Aw = share of the smaller zone's perimeter that is open.")
    print("  * = above Annex 20's %.1f transition: boundary-layer driven, not"
          % AW_DENSITY_DRIVEN_MAX)
    print("    the bulk-density regime Brown & Solvason describes. The rate is")
    print("    extrapolation there -- and the measured trend is towards the")
    print("    zones equalising MORE, not less.")
    print()
    print("  dT@1kW is what the FIXED rate produces under a 1 kW imbalance:")
    print("  ZoneMixing is linear, so dT scales as 1/ACH. That column is the")
    print("  one to read before capping anything.")
    print()
    print("  It is per PAIR, so it is pessimistic for a space with several")
    print("  boundaries: 101a has two, and the two mixing objects add, so its")
    print("  real split under 1 kW is about half what its rows show.")
    print()
    print("  v is the mean speed through half the opening -- Q / (A/2) -- the")
    print("  sanity check on the rates. A few cm/s is a barely perceptible")
    print("  draft; the ACH looks large only because these upper zones are")
    print("  small next to the openings that feed them.")
    print()

    for r in results:
        print("  %s" % r["construction_name"])
        print("      %s <-> %s   (smaller: %s)"
              % (r["space_a"], r["space_b"], r["smaller_space"]))
        if r["kind"] == "corridor":
            print("      cross-section: w/L %.2f, w/W_corridor %.2f%s"
                  % (r["narrow_ratio"], r["span_ratio"],
                     "" if r["partner_open"] else "   <- far side is a room"))
        print("      %s" % ",".join(r["surface_names"]))
    print()

    for message in warnings:
        print("WARNING: %s" % message)
    if warnings:
        print()

    overrides = attention["declared_open"] + attention["declared_solid"]
    if overrides:
        print("=" * 72)
        print("ENGINEER OVERRIDES -- %d surface(s) set by hand, not derived"
              % len(overrides))
        print("=" * 72)
        for op in attention["declared_solid"]:
            print("    SOLID  %-12s %-30s -> %s"
                  % (op["surface_a"], op["space_a"], op["space_b"]))
        for op in attention["declared_open"]:
            print("    OPEN   %-12s %-30s -> %s"
                  % (op["surface_a"], op["space_a"], op["space_b"]))
        print()
        print("  These are your judgement, not the plan's. Nothing in the")
        print("  geometry says a wall is fire-rated, or which end of a stair")
        print("  the flight arrives at, so the rules cannot reach them and")
        print("  cannot check them either.")
        print()
        print("  Each named surface takes its PARTNER with it -- an air")
        print("  boundary is a property of the pair, and half of one would")
        print("  mean nothing. A promoted surface joins the construction")
        print("  already covering its space pair rather than starting a")
        print("  second one, because two constructions across one pair of")
        print("  zones would give EnergyPlus two mixing objects and double")
        print("  the flow.")
        print()
        print("  Re-check these after a full rebuild: surface names are")
        print("  OpenStudio's, and a rebuild reassigns them -- a few land")
        print("  differently even for identical input. An incremental")
        print("  update_osm_geometry.py --apply preserves them.")
        print()

    stacked = attention["corridor_rejected"]
    if stacked:
        print("=" * 72)
        print("REJECTED -- %d cross-section(s) open at two storeys in one plane"
              % len(stacked))
        print("=" * 72)
        for op in stacked:
            print("    %-12s %-34s z %.2f-%.2f"
                  % (op["surface_a"], op["space_b"],
                     op["z_range"][0], op["z_range"][1]))
        print()
        print("  These cut across %s in the same plane but open to rooms on"
              % stacked[0]["space_a"])
        print("  different storeys. Both cannot be open: something has to stop")
        print("  a person walking out of the upper room into the void. In real")
        print("  construction the upper one is a guardrail over a wall below,")
        print("  or there is no upper opening at all -- either way it is a")
        print("  special case, so neither is assigned.")
        print()
        print("  If the upper one really is a guardrail, say so the way the")
        print("  bridge already understands: label that upper room as a")
        print("  mezzanine and rule 2 will pick up its edge.")
        print()

    stair_ends = attention["open_stair_ends"]
    if stair_ends:
        print("=" * 72)
        print("YOUR CALL -- %d open-stair END(s), one per storey is a wall"
              % len(stair_ends))
        print("=" * 72)
        for op in stair_ends:
            print("    %-12s %-30s -> %-34s"
                  % (op["surface_a"], op["space_a"], op["space_b"]))
        print()
        print("  A stair opens at ONE end per storey and is walled at the")
        print("  other -- you step onto the flight at the bottom and off it at")
        print("  the top, and those are opposite ends. Which is which is drawn")
        print("  as a direction arrow the exported plan does not carry, so")
        print("  none of these is assigned.")
        print()
        print("  The SIDES of the same stair are taken automatically: a long")
        print("  edge open at two storeys is an ordinary double-height")
        print("  guardrail, and carries no such ambiguity.")
        print()
        print("  Record your decision here rather than assigning by hand,")
        print("  so the run reproduces -- the chosen end is then sized and")
        print("  grouped with the sides of the same pair:")
        print("      --open-surface %r"
              % ",".join(op["surface_a"] for op in stair_ends))
        print()

    dead_ends = [r for r in results
                 if r["kind"] == "corridor" and not r["partner_open"]]
    if dead_ends:
        print("=" * 72)
        print("CONFIRM THESE %d CORRIDOR END(S) -- the drawing cannot settle them"
              % len(dead_ends))
        print("=" * 72)
        for r in dead_ends:
            print("    %-38s -> %s" % (r["construction_name"], r["space_b"]))
        print()
        print("  Each of these is a full cross-section of the corridor, square")
        print("  to its run: geometrically identical to the ends that open")
        print("  into a lobby or another corridor. But the far side is an")
        print("  enclosed room, so it may be a real wall with a door in it.")
        print()
        print("  Nothing in the plan distinguishes the two cases -- a corridor")
        print("  dead-ending into an office and one opening into a lobby draw")
        print("  the same. Only you can say which this is.")
        print()
        print("  To drop one, re-run with:")
        print("      --corridor-exclude %r"
              % "|".join(sorted({r["space_b"] for r in dead_ends})))
        print()

    print("=" * 72)
    print("REVIEW THESE ASSUMPTIONS -- the rates above are sized, not measured")
    print("=" * 72)
    print("  driving dT      %.1f K across every opening, always on" % args.delta_t)
    print("  mean air temp   %.2f K" % args.t_mean)
    print("  vertical Cd     %.2f   Q = (Cd/3) W H^1.5 sqrt(g dT / T)"
          % CD_VERTICAL)
    print("  horizontal C    %.3f  Q = C sqrt((g dT / T) D^5)   [Epstein, "
          "thin plate]" % C_HORIZONTAL)
    print("  ACH basis       volume of the SMALLER zone, per Energy+.idd")
    if corridor:
        print("  corridor cut    w/L <= %.2f, w/W_corridor = 1 +/- %.2f, "
              "|cos| <= %.2f"
              % (args.corridor_narrow_ratio, args.corridor_span_tol,
                 args.corridor_square_cos))
        print("                  narrow alone is not enough: on 101a the")
        print("                  NARROWEST wall (1.29 m to office 102) is a")
        print("                  wall, and the two open ends are wider.")
    print()
    print("  dT is not a free parameter. An air boundary is used exactly")
    print("  where two zones are open to each other, and the exchange above")
    print("  is what holds them together, so they equilibrate -- 0.5 K is the")
    print("  accepted working figure. A large dT and an open boundary are")
    print("  mutually exclusive: 10 K between adjacent commercial zones means")
    print("  an enclosure, a cold store or a sauna, and those do not have an")
    print("  open boundary. --delta-t is for an engineer's judgement on a")
    print("  genuine edge case, not for exploring a range.")
    print()
    print("  Note the consistency: the rates are high, and that is precisely")
    print("  why the 0.5 K premise holds. Q scales with sqrt(dT), so even a")
    print("  4x error in dT moves every rate by only 2x.")
    print()
    print("  For comparison, EnergyPlus's default is %.1f ACH -- which for"
          % EPLUS_DEFAULT_ACH)
    print("  these openings is low by two orders of magnitude.")

    out_of_regime = [r for r in results
                     if r["aperture_width_ratio"] > AW_DENSITY_DRIVEN_MAX]
    if out_of_regime:
        print()
        print("-" * 72)
        print("%d pair(s) above Aw = %.1f -- extrapolated, not validated:"
              % (len(out_of_regime), AW_DENSITY_DRIVEN_MAX))
        for r in out_of_regime:
            print("    %-38s Aw %.2f  %6.1f ACH"
                  % (r["construction_name"], r["aperture_width_ratio"],
                     r["recommended_ach"]))
        print()
        print("  Annex 20 Fig. 2.16: Scott et al. had to shrink Aw below 0.1")
        print("  to block the boundary-layer flow and drive the two zones to")
        print("  different temperatures at all. Past that ratio the flow runs")
        print("  in boundary layers at the top and bottom of the aperture")
        print("  rather than as the bulk counterflow this correlation")
        print("  describes, and the isothermality factor dT/dTw collapses")
        print("  towards zero -- the zones equalise MORE, not less. So these")
        print("  rates are extrapolation, but they err towards too little")
        print("  coupling, not too much.")
        print()
        print("  Which cuts both ways against the cap below: the sizing here")
        print("  is if anything conservative, so the applied rate is a")
        print("  deliberate choice about transient headroom rather than a")
        print("  hedge against the correlation being wrong.")

    capped = [r for r in results if r["capped"]]
    if capped:
        print()
        print("=" * 72)
        print("RATE LIMIT APPLIED -- %d of %d pair(s) capped at %.1f ACH"
              % (len(capped), len(results), args.max_ach))
        print("=" * 72)
        for r in capped:
            print("    %-38s %6.1f -> %5.1f ACH   dT@1kW %5.2f -> %5.2fK"
                  % (r["construction_name"], r["uncapped_ach"],
                     r["recommended_ach"], r["uncapped_delta_t_at_1kw"],
                     r["delta_t_at_1kw"]))
        print()
        print("  This is NOT a correction to the sizing above. It is what")
        print("  keeps the model able to show you a transient.")
        print()
        print("  An air boundary has two jobs that pull against each other:")
        print("  couple the zones at steady state, and stay loose enough that")
        print("  a transient can briefly override the coupling. At the sized")
        print("  rate a solar gain landing on a mezzanine is absorbed into")
        print("  the space below within the timestep and never reaches the")
        print("  results. That excursion cannot be computed in advance --")
        print("  it is the reason to run the simulation at all.")
        print()
        print("  At %.1f ACH an ordinary imbalance still couples tightly:"
              % args.max_ach)
        for r in capped[:1]:
            watts = 100.0
            dt = r["delta_t_at_1kw"] * watts / 1000.0
            print("    %.0f W across %s settles at %.2f K."
                  % (watts, r["smaller_space"], dt))
        print()
        print("  So read a large sustained split in the RESULTS as a finding")
        print("  about the design -- stratification, a mezzanine that wants")
        print("  its own equipment -- and not as an artefact of this rate.")
        print("  Raise --max-ach only if you have decided that excursion is")
        print("  not real; 0 disables the cap entirely.")

    return 1 if warnings else 0


if __name__ == "__main__":
    sys.exit(main())
