# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (C) 2026 the FreeCAD-OpenStudio bridge contributors
#
# This program is free software: you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the
# Free Software Foundation, either version 3 of the License, or (at your
# option) any later version.  See LICENSE for the full text.

"""Tests for what an elevation sketch hangs off.

Run under the bridge venv:

    osvenv/Scripts/python.exe -m unittest discover -s tests -v

These sketches used to attach to the largest imported wall face with MapMode
FlatFace.  That reads well -- the sketch plane *is* the wall -- and it is a
trap, because `import` replaces a surface's Shape outright and FlatFace then
re-derives the frame from a new face whose parametrisation need not match the
old one.  Measured: re-importing after a roof change turned three sketches
through 180 degrees and slid them up to 39 m, dragging 20 of 27 drawn outlines
into positions nobody drew, with nothing downstream to question it.

So the sketch now stands on the traced wall centerline instead, and the plan
is not regenerated by anything.  What is worth pinning down here is the
choice of line: the right one, from the right storey, and a refusal rather
than a guess when the plan cannot supply it -- ThreePointsNormal needs a third
point off the line, and three collinear points raise rather than return a bad
plane.
"""

import math
import os
import sys
import types
import unittest

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))


class Vector(object):
    """Enough of FreeCAD.Vector for the selection logic under test."""

    def __init__(self, x=0.0, y=0.0, z=0.0):
        if isinstance(x, Vector):
            x, y, z = x.x, x.y, x.z
        self.x, self.y, self.z = float(x), float(y), float(z)

    @property
    def Length(self):
        return math.sqrt(self.x ** 2 + self.y ** 2 + self.z ** 2)

    def __sub__(self, other):
        return Vector(self.x - other.x, self.y - other.y, self.z - other.z)

    def __mul__(self, scale):
        return Vector(self.x * scale, self.y * scale, self.z * scale)

    def dot(self, other):
        return self.x * other.x + self.y * other.y + self.z * other.z

    def normalize(self):
        length = self.Length
        if length:
            self.x, self.y, self.z = (self.x / length, self.y / length,
                                      self.z / length)
        return self


_freecad = sys.modules.setdefault("FreeCAD", types.ModuleType("FreeCAD"))
_freecad.Vector = Vector
_freecad.Placement = object
sys.modules.setdefault("Part", types.ModuleType("Part"))
_bop = sys.modules.setdefault("BOPTools", types.ModuleType("BOPTools"))
if not hasattr(_bop, "SplitAPI"):
    _bop.SplitAPI = types.SimpleNamespace()
sys.modules.setdefault("Sketcher", types.ModuleType("Sketcher"))

import fc_seed_openings as fso  # noqa: E402


class Vertex(object):
    def __init__(self, point):
        self.Point = point


class Edge(object):
    def __init__(self, a, b):
        self.Vertexes = [Vertex(a), Vertex(b)]


class Shape(object):
    def __init__(self, edges):
        self.Edges = edges
        self.Vertexes = [v for e in edges for v in e.Vertexes]


class Length(object):
    """Enough of FreeCAD's Quantity for the length readers under test.

    The story properties are App::PropertyLength now, so they read back as a
    Quantity that knows its own unit rather than a bare number that has to be
    assumed to be metres.  Stubbing the Quantity keeps these tests on the same
    code path the document takes.
    """

    def __init__(self, metres):
        self._metres = float(metres)

    def getValueAs(self, unit):
        assert unit == "m", unit
        return self._metres


class PlanSketch(object):
    """A traced storey: a closed rectangle of wall centerlines."""

    def __init__(self, label, elevation=0.0, x0=0.0, x1=50.0,
                 y0=0.0, y1=18.0, extra=()):
        self.Label = label
        self.OS_Elevation = Length(elevation)
        corners = [Vector(x0, y0), Vector(x1, y0),
                   Vector(x1, y1), Vector(x0, y1)]
        edges = [Edge(corners[i], corners[(i + 1) % 4]) for i in range(4)]
        edges.extend(extra)
        self.Shape = Shape(edges)


def group(normal, offset):
    return {"normal": Vector(*normal), "offset": offset}


class WallLineTests(unittest.TestCase):

    def setUp(self):
        self.plan = PlanSketch("FirstFP Sketch")

    def find(self, sketches, normal, offset):
        return fso.plan_wall_edge(sketches, group(normal, offset))

    def test_the_south_wall(self):
        found = self.find([self.plan], (0, -1, 0), 0.0)
        self.assertIsNotNone(found)
        plan, edge, vertex = found
        self.assertIs(plan, self.plan)
        self.assertEqual(edge, 1)               # the y = 0 run

    def test_the_west_wall(self):
        _plan, edge, _v = self.find([self.plan], (-1, 0, 0), 0.0)
        self.assertEqual(edge, 4)               # the x = 0 run

    def test_the_north_wall_matches_on_its_own_offset(self):
        _plan, edge, _v = self.find([self.plan], (0, 1, 0), 18.0)
        self.assertEqual(edge, 3)

    def test_a_plane_the_plan_does_not_draw_finds_nothing(self):
        """An interior court, or a wall the intersection invented.

        Returning None is the point: the caller falls back and says so,
        rather than attaching the facade to whichever line was nearest.
        """
        self.assertIsNone(self.find([self.plan], (0, 1, 0), 9.0))

    def test_the_longest_run_in_the_plane_wins(self):
        """A facade line, not the stub beside a doorway that shares it."""
        stub = Edge(Vector(2.0, 0.0), Vector(3.0, 0.0))
        plan = PlanSketch("FirstFP Sketch", extra=[stub])
        _p, edge, _v = fso.plan_wall_edge([plan], group((0, -1, 0), 0.0))
        self.assertEqual(edge, 1)               # the 50 m run, not the 1 m one

    def test_the_lowest_storey_wins(self):
        """Both storeys share the footprint; the base is the datum."""
        upper = PlanSketch("SecondFP Sketch", elevation=3.38)
        lower = PlanSketch("FirstFP Sketch", elevation=0.0)
        plan, _e, _v = fso.plan_wall_edge([upper, lower],
                                          group((0, -1, 0), 0.0))
        self.assertIs(plan, lower)

    def test_the_third_point_is_the_furthest_from_the_line(self):
        """ThreePointsNormal needs a point off the line, and the furthest one
        is both the least degenerate and the same choice every run."""
        _p, _e, vertex = self.find([self.plan], (0, -1, 0), 0.0)
        point = self.plan.Shape.Vertexes[vertex - 1].Point
        self.assertAlmostEqual(point.y, 18.0, 9)

    def test_a_plan_that_is_only_one_line_is_refused(self):
        """Three collinear points cannot define a plane, and FreeCAD raises
        rather than returning a bad one -- so this must not reach it."""
        line = PlanSketch.__new__(PlanSketch)
        line.Label, line.OS_Elevation = "Scratch", Length(0.0)
        line.Shape = Shape([Edge(Vector(0.0, 0.0), Vector(50.0, 0.0))])
        self.assertIsNone(fso.plan_wall_edge([line], group((0, -1, 0), 0.0)))

    def test_a_sketch_with_no_shape_is_skipped(self):
        empty = PlanSketch.__new__(PlanSketch)
        empty.Label, empty.OS_Elevation, empty.Shape = ("Empty",
                                                        Length(0.0), None)
        _p, edge, _v = fso.plan_wall_edge([empty, self.plan],
                                          group((0, -1, 0), 0.0))
        self.assertEqual(edge, 1)

    def test_a_line_off_the_plane_is_not_a_match(self):
        """Both endpoints have to be in the plane, not just one."""
        angled = Edge(Vector(0.0, 0.0), Vector(10.0, 5.0))
        plan = PlanSketch.__new__(PlanSketch)
        plan.Label, plan.OS_Elevation = "FirstFP Sketch", Length(0.0)
        plan.Shape = Shape([angled, Edge(Vector(0.0, 9.0), Vector(9.0, 9.0))])
        self.assertIsNone(fso.plan_wall_edge([plan], group((0, -1, 0), 0.0)))


class FakeSketch(object):
    """A sketch whose external geometry is grouped by object, as FreeCAD's is.

    That grouping is the whole reason strip_external cannot walk the entry
    indices: delExternal removes one *element*, while ExternalGeometry lists
    them bundled per object, so one entry can take four calls to clear.
    """

    def __init__(self, bundles, constraints_per_element=1):
        self.elements = [(name, sub) for name, subs in bundles for sub in subs]
        self.Constraints = list(range(len(self.elements)
                                      * constraints_per_element))
        self.per_element = constraints_per_element

    @property
    def ExternalGeometry(self):
        grouped = {}
        for name, sub in self.elements:
            grouped.setdefault(name, []).append(sub)
        return [(name, tuple(subs)) for name, subs in grouped.items()]

    def delExternal(self, index):
        del self.elements[index]
        for _ in range(self.per_element):
            if self.Constraints:
                self.Constraints.pop()


class StripExternalTests(unittest.TestCase):

    def test_every_element_goes_not_just_every_entry(self):
        """Walking the entry indices left two thirds of them behind.

        The first version deleted len(ExternalGeometry) times -- once per
        object -- and reported success while 23 of 32 references survived.
        """
        sketch = FakeSketch([("Surface 120", ("Edge1", "Edge2", "Edge3",
                                              "Edge4")),
                             ("Surface 151", ("Edge1", "Edge2", "Edge3"))])
        removed, lost = fso.strip_external(sketch)
        self.assertEqual(removed, 7)
        self.assertEqual(sketch.ExternalGeometry, [])

    def test_the_constraints_that_referenced_them_are_counted(self):
        sketch = FakeSketch([("Surface 5", ("Edge1", "Edge2"))],
                            constraints_per_element=2)
        _removed, lost = fso.strip_external(sketch)
        self.assertEqual(lost, 4)

    def test_a_sketch_with_none_is_left_alone(self):
        sketch = FakeSketch([])
        self.assertEqual(fso.strip_external(sketch), (0, 0))

    def test_a_delete_that_never_shrinks_the_list_gives_up(self):
        """Bounded rather than trusting the API to make progress."""
        class Stuck(FakeSketch):
            def delExternal(self, index):
                pass

        sketch = Stuck([("Surface 5", ("Edge1",))])
        removed, _lost = fso.strip_external(sketch)
        self.assertEqual(removed, 10000)


class Named(object):
    """An object the way an ExternalGeometry entry holds one."""

    def __init__(self, name):
        self.Name = self.Label = name


class RefSketch(object):
    """Grouped external geometry, entries holding objects rather than names.

    The real property is [(object, (sub, sub, ...)), ...] -- that is what
    external_refs has to flatten and what foreign_external has to look inside.
    """

    def __init__(self, bundles, fail=False):
        self.elements = [(obj, sub) for obj, subs in bundles for sub in subs]
        self.fail = fail

    @property
    def ExternalGeometry(self):
        grouped, order = {}, []
        for obj, sub in self.elements:
            if obj.Name not in grouped:
                grouped[obj.Name] = (obj, [])
                order.append(obj.Name)
            grouped[obj.Name][1].append(sub)
        return [(grouped[n][0], tuple(grouped[n][1])) for n in order]

    def addExternal(self, name, sub):
        if self.fail:
            raise ValueError("cannot reference %s" % sub)
        self.elements.append((Named(name), sub))


PLAN = Named("Sketch")
OTHER_PLAN = Named("Sketch001")
IMPORTED = Named("Surface 120")


class ExternalReferenceTests(unittest.TestCase):
    """What an elevation sketch is allowed to point at.

    Only the plan.  These used to project the imported facade's edges in as
    snap targets, which is a reference to the model inside a sketch that has
    to depend only on the drawing -- and to the one kind of geometry `import`
    replaces outright.  What goes in now is the wall centerline the sketch is
    already attached to, so the thing you snap to and the thing the sketch
    stands on cannot come apart.
    """

    def test_refs_are_flattened_out_of_their_bundles(self):
        sketch = RefSketch([(PLAN, ("Edge1",)),
                            (IMPORTED, ("Edge1", "Edge2", "Edge3"))])
        self.assertEqual(
            [(obj.Name, sub) for obj, sub in fso.external_refs(sketch)],
            [("Sketch", "Edge1"), ("Surface 120", "Edge1"),
             ("Surface 120", "Edge2"), ("Surface 120", "Edge3")])

    def test_only_the_model_references_count_as_foreign(self):
        sketch = RefSketch([(PLAN, ("Edge1",)),
                            (OTHER_PLAN, ("Edge48",)),
                            (IMPORTED, ("Edge1", "Edge2"))])
        foreign = fso.foreign_external(sketch, {"Sketch", "Sketch001"})
        self.assertEqual([sub for _obj, sub in foreign], ["Edge1", "Edge2"])

    def test_a_sketch_referencing_only_the_plan_has_nothing_foreign(self):
        sketch = RefSketch([(PLAN, ("Edge1",))])
        self.assertEqual(fso.foreign_external(sketch, {"Sketch"}), [])

    def test_the_plan_line_is_added_when_it_is_missing(self):
        sketch = RefSketch([])
        self.assertEqual(fso.add_plan_edge(sketch, (PLAN, 1)), 1)
        self.assertEqual(
            [(obj.Name, sub) for obj, sub in fso.external_refs(sketch)],
            [("Sketch", "Edge1")])

    def test_adding_it_twice_does_nothing_the_second_time(self):
        """Re-seeding must not cost a constraint made against the datum line,
        which draining and re-adding would."""
        sketch = RefSketch([(PLAN, ("Edge1",))])
        self.assertEqual(fso.add_plan_edge(sketch, (PLAN, 1)), 0)
        self.assertEqual(len(fso.external_refs(sketch)), 1)

    def test_a_different_edge_of_the_same_plan_is_still_added(self):
        """Matching on the object alone would leave a sketch whose wall line
        changed pointing at the old one."""
        sketch = RefSketch([(PLAN, ("Edge7",))])
        self.assertEqual(fso.add_plan_edge(sketch, (PLAN, 1)), 1)
        self.assertEqual(len(fso.external_refs(sketch)), 2)

    def test_no_anchor_means_nothing_to_project(self):
        """The fallback attachment, where the plan draws no line in this
        plane, has no plan edge to offer."""
        sketch = RefSketch([])
        self.assertEqual(fso.add_plan_edge(sketch, None), 0)
        self.assertEqual(fso.external_refs(sketch), [])

    def test_a_refused_reference_is_reported_not_raised(self):
        """One facade that will not take the reference must not abandon the
        other six."""
        sketch = RefSketch([], fail=True)
        self.assertEqual(fso.add_plan_edge(sketch, (PLAN, 1)), 0)


if __name__ == "__main__":
    unittest.main()
